export const venues = [
  {
    id: '1',
    name: 'Prestige Fitness Club',
    rating: 4.8,
    reviews: 620,
    address: 'Centre Ville, Tetouan',
    image: '',
    coordinate: { latitude: 35.5785, longitude: -5.3684 },
    type: 'Fitness',
    price: 350,
    gender: 'Everyone',
  },
  {
    id: '2',
    name: 'Belle Femme Salon',
    rating: 4.9,
    reviews: 710,
    address: 'Wilaya, Tetouan',
    image: '',
    coordinate: { latitude: 35.5731, longitude: -5.3619 },
    type: 'Beauty',
    price: 250,
    gender: 'Female only',
  },
  {
    id: '3',
    name: 'Tetouan Marine',
    rating: 4.5,
    reviews: 150,
    address: "M'diq, Tetouan",
    image: '',
    coordinate: { latitude: 35.6819, longitude: -5.3254 },
    type: 'Motors & Watercraft',
    price: 1200,
    gender: 'Everyone',
  },
  {
    id: '4',
    name: 'Serenity Spa & Wellness',
    rating: 4.7,
    reviews: 450,
    address: 'Martil, Tetouan',
    image: '',
    coordinate: { latitude: 35.6167, longitude: -5.2667 },
    type: 'Wellness',
    price: 500,
    gender: 'Everyone',
  },
  {
    id: '5',
    name: 'Powerhouse Gym',
    rating: 4.6,
    reviews: 800,
    address: 'Cabo Negro, Tetouan',
    image: '',
    coordinate: { latitude: 35.6500, longitude: -5.3000 },
    type: 'Fitness',
    price: 400,
    gender: 'Everyone',
  },
  {
    id: '6',
    name: 'Glamour Touch Beauty Center',
    rating: 5.0,
    reviews: 950,
    address: 'Centre Ville, Tetouan',
    image: '',
    coordinate: { latitude: 35.5760, longitude: -5.3690 },
    type: 'Beauty',
    price: 300,
    gender: 'Female only',
  },
  {
    id: '7',
    name: 'Nautica Jet Ski',
    rating: 4.3,
    reviews: 95,
    address: 'Marina Smir, Tetouan',
    image: '',
    coordinate: { latitude: 35.7167, longitude: -5.3167 },
    type: 'Motors & Watercraft',
    price: 1500,
    gender: 'Everyone',
  },
  {
    id: '8',
    name: 'The Wellness Hub',
    rating: 4.8,
    reviews: 380,
    address: 'Wilaya, Tetouan',
    image: '',
    coordinate: { latitude: 35.5710, longitude: -5.3650 },
    type: 'Wellness',
    price: 450,
    gender: 'Everyone',
  },
  {
    id: '9',
    name: 'Iron Temple Gym',
    rating: 4.9,
    reviews: 1100,
    address: 'Martil, Tetouan',
    image: '',
    coordinate: { latitude: 35.6200, longitude: -5.2750 },
    type: 'Fitness',
    price: 300,
    gender: 'Male only',
  },
  {
    id: '10',
    name: 'Elegance Beauty Clinic',
    rating: 4.7,
    reviews: 550,
    address: 'Cabo Negro, Tetouan',
    image: '',
    coordinate: { latitude: 35.6525, longitude: -5.3050 },
    type: 'Beauty',
    price: 400,
    gender: 'Female only',
  },
  {
    id: '11',
    name: 'Zenith Yoga & Pilates',
    rating: 4.9,
    reviews: 250,
    address: 'Centre Ville, Tetouan',
    image: '',
    coordinate: { latitude: 35.5795, longitude: -5.3675 },
    type: 'Wellness',
    price: 200,
    gender: 'Everyone',
  },
  {
    id: '12',
    name: "Athlete's Corner",
    rating: 4.5,
    reviews: 680,
    address: 'Wilaya, Tetouan',
    image: '',
    coordinate: { latitude: 35.5742, longitude: -5.3601 },
    type: 'Fitness',
    price: 250,
    gender: 'Everyone',
  },
  {
    id: '13',
    name: 'La Belleza Salon',
    rating: 4.6,
    reviews: 480,
    address: 'Martil, Tetouan',
    image: '',
    coordinate: { latitude: 35.6182, longitude: -5.2693 },
    type: 'Beauty',
    price: 200,
    gender: 'Female only',
  },
  {
    id: '14',
    name: 'Ocean Breeze Spa',
    rating: 4.8,
    reviews: 320,
    address: "M'diq, Tetouan",
    image: '',
    coordinate: { latitude: 35.6835, longitude: -5.3240 },
    type: 'Wellness',
    price: 600,
    gender: 'Everyone',
  },
  {
    id: '15',
    name: 'Fit Factory Tetouan',
    rating: 4.7,
    reviews: 900,
    address: 'Centre Ville, Tetouan',
    image: '',
    coordinate: { latitude: 35.5770, longitude: -5.3660 },
    type: 'Fitness',
    price: 320,
    gender: 'Everyone',
  },
  {
    id: '16',
    name: 'The Nail Bar',
    rating: 4.9,
    reviews: 850,
    address: 'Wilaya, Tetouan',
    image: '',
    coordinate: { latitude: 35.5720, longitude: -5.3630 },
    type: 'Beauty',
    price: 150,
    gender: 'Female only',
  },
  {
    id: '17',
    name: 'Marina Bay Boats',
    rating: 4.2,
    reviews: 80,
    address: 'Marina Smir, Tetouan',
    image: '',
    coordinate: { latitude: 35.7180, longitude: -5.3150 },
    type: 'Motors & Watercraft',
    price: 2500,
    gender: 'Everyone',
  },
  {
    id: '18',
    name: 'Holistic Harmony Center',
    rating: 4.9,
    reviews: 410,
    address: 'Cabo Negro, Tetouan',
    image: '',
    coordinate: { latitude: 35.6550, longitude: -5.3080 },
    type: 'Wellness',
    price: 550,
    gender: 'Everyone',
  },
  {
    id: '19',
    name: 'CrossFit Tetouan',
    rating: 4.8,
    reviews: 750,
    address: 'Martil, Tetouan',
    image: '',
    coordinate: { latitude: 35.6215, longitude: -5.2780 },
    type: 'Fitness',
    price: 450,
    gender: 'Everyone',
  },
  {
    id: '20',
    name: "Gentlemen's Barber Club",
    rating: 4.9,
    reviews: 600,
    address: 'Centre Ville, Tetouan',
    image: '',
    coordinate: { latitude: 35.5755, longitude: -5.3695 },
    type: 'Beauty',
    price: 100,
    gender: 'Male only',
  },
  {
    id: '21',
    name: 'Mind & Body Studio',
    rating: 4.7,
    reviews: 300,
    address: 'Wilaya, Tetouan',
    image: '',
    coordinate: { latitude: 35.5705, longitude: -5.3645 },
    type: 'Wellness',
    price: 280,
    gender: 'Everyone',
  }
];
